language: java

jdk:
 - oraclejdk7
 - openjdk7
 - oraclejdk8

env:
- TERM=dumb

install: ./gradlew assemble --stacktrace --info
script: ./gradlew check jacocoTestReport --stacktrace --debug --continue
after_success: ./gradlew coveralls --stacktrace --info
